#!/usr/bin/env bash
set -Eeuo pipefail

INSTALL_DIR="/opt/autobook-linux"
CONFIG_DIR="/etc/linux-autobook"
ADMIN_PORT="8766"
ADMIN_BIND="0.0.0.0"
PUBLIC_HOST=""
DOMAIN=""
ACME_EMAIL=""
ROLE=""
ACTION=""
GATEWAY_URL=""
GATEWAY_TOKEN=""
GATEWAY_CA_FILE=""
PURGE=0
NON_INTERACTIVE=0
REPO_URL_OVERRIDE="${AUTOBOOK_REPO_URL:-}"
REPO_BRANCH_OVERRIDE="${AUTOBOOK_BRANCH:-}"
REPO_URL="${REPO_URL_OVERRIDE:-https://github.com/moli-xia/linux-autobook.git}"
REPO_BRANCH="${REPO_BRANCH_OVERRIDE:-main}"
SOURCE_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

usage() {
  cat <<'EOF'
Usage: sudo bash install.sh [options]

Without options an interactive Chinese menu is displayed.

  --action install|update|status|uninstall
  --role all|gateway|worker
  --domain DOMAIN              Obtain an auto-renewed Let's Encrypt certificate
  --acme-email EMAIL           Optional certificate expiry email
  --public-host HOST           Link/certificate host when no domain is used
  --admin-port PORT
  --admin-bind ADDRESS
  --gateway-url HTTPS_URL      Worker-only central gateway URL
  --gateway-token TOKEN        Shared gateway token
  --gateway-ca-file PATH       Private/self-signed gateway CA path
  --install-dir PATH
  --purge                      Uninstall without creating a config/data backup
  --non-interactive
EOF
}

while (($#)); do
  case "$1" in
    --action) ACTION="${2:-}"; shift 2 ;;
    --role) ROLE="${2:-}"; shift 2 ;;
    --domain) DOMAIN="${2:-}"; shift 2 ;;
    --acme-email) ACME_EMAIL="${2:-}"; shift 2 ;;
    --public-host) PUBLIC_HOST="${2:-}"; shift 2 ;;
    --admin-port) ADMIN_PORT="${2:-}"; shift 2 ;;
    --admin-bind) ADMIN_BIND="${2:-}"; shift 2 ;;
    --gateway-url) GATEWAY_URL="${2:-}"; shift 2 ;;
    --gateway-token) GATEWAY_TOKEN="${2:-}"; shift 2 ;;
    --gateway-ca-file) GATEWAY_CA_FILE="${2:-}"; shift 2 ;;
    --install-dir) INSTALL_DIR="${2:-}"; shift 2 ;;
    --purge) PURGE=1; shift ;;
    --non-interactive) NON_INTERACTIVE=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown argument: $1" >&2; usage; exit 2 ;;
  esac
done

if [[ "${EUID}" -ne 0 ]]; then
  echo "Please run as root: sudo bash install.sh" >&2
  exit 1
fi

validate_common() {
  if [[ ! "$ADMIN_PORT" =~ ^[0-9]{1,5}$ ]] || ((ADMIN_PORT < 1 || ADMIN_PORT > 65535)); then
    echo "Invalid admin port: $ADMIN_PORT" >&2; exit 2
  fi
  if [[ ! "$INSTALL_DIR" =~ ^/[A-Za-z0-9._/-]+$ || "$INSTALL_DIR" == "/" ]]; then
    echo "Invalid install directory: $INSTALL_DIR" >&2; exit 2
  fi
  if [[ ! "$CONFIG_DIR" =~ ^/[A-Za-z0-9._/-]+$ || "$CONFIG_DIR" == "/" ]]; then
    echo "Invalid config directory: $CONFIG_DIR" >&2; exit 2
  fi
  if [[ ! "$ADMIN_BIND" =~ ^[A-Za-z0-9.:-]+$ ]]; then
    echo "Invalid admin bind address: $ADMIN_BIND" >&2; exit 2
  fi
  if [[ -n "$DOMAIN" && ! "$DOMAIN" =~ ^[A-Za-z0-9]([A-Za-z0-9.-]*[A-Za-z0-9])?$ ]]; then
    echo "Invalid domain: $DOMAIN" >&2; exit 2
  fi
  if [[ -n "$PUBLIC_HOST" && ! "$PUBLIC_HOST" =~ ^[A-Za-z0-9._:-]+$ ]]; then
    echo "Invalid public host: $PUBLIC_HOST" >&2; exit 2
  fi
  if [[ -n "$GATEWAY_URL" ]] \
    && [[ ! "$GATEWAY_URL" =~ ^https://[A-Za-z0-9._:-]+/?$ ]] \
    && [[ ! "$GATEWAY_URL" =~ ^https://\[[0-9A-Fa-f:]+\](:[0-9]+)?/?$ ]]; then
      echo "Gateway URL must be a simple HTTPS origin: $GATEWAY_URL" >&2; exit 2
  fi
  if [[ -n "$GATEWAY_TOKEN" && ! "$GATEWAY_TOKEN" =~ ^[A-Za-z0-9._~-]{16,256}$ ]]; then
    echo "Gateway token must be 16-256 safe characters" >&2; exit 2
  fi
}

choose_action() {
  echo
  echo "========== linux-autobook 管理菜单 =========="
  echo "1) 安装或重新配置"
  echo "2) 更新程序（保留配置和数据）"
  echo "3) 查看安装状态"
  echo "4) 卸载"
  echo "0) 退出"
  read -r -p "请选择 [1]: " choice
  case "${choice:-1}" in
    1) ACTION="install" ;; 2) ACTION="update" ;; 3) ACTION="status" ;;
    4) ACTION="uninstall" ;; 0) exit 0 ;; *) echo "无效选项" >&2; exit 2 ;;
  esac
}

choose_role() {
  echo
  echo "选择本机角色："
  echo "1) 网关 + Worker（单机，推荐首次部署）"
  echo "2) 仅百度下载网关（中心节点）"
  echo "3) 仅 Worker（计算节点，可部署多台）"
  read -r -p "请选择 [1]: " choice
  case "${choice:-1}" in
    1) ROLE="all" ;; 2) ROLE="gateway" ;; 3) ROLE="worker" ;;
    *) echo "无效角色" >&2; exit 2 ;;
  esac
}

load_install_state() {
  local state="/etc/linux-autobook/install.env"
  if [[ -r "$state" ]]; then
    # Generated by this installer and writable only by root.
    # shellcheck disable=SC1090
    source "$state"
    INSTALL_DIR="${INSTALL_DIR:-/opt/autobook-linux}"
    CONFIG_DIR="${CONFIG_DIR:-/etc/linux-autobook}"
  fi
}

show_status() {
  load_install_state
  echo "Install directory: $INSTALL_DIR"
  echo "Config directory:  $CONFIG_DIR"
  if [[ -r "$CONFIG_DIR/install.env" ]]; then
    echo "Role:              ${INSTALL_ROLE:-unknown}"
    echo "TLS mode:          ${TLS_MODE:-unknown}"
    echo "Public host:       ${PUBLIC_HOST:-unknown}"
  else
    echo "State:             not installed"
  fi
  for unit in autobook-admin autobook-gateway autobook-worker; do
    if systemctl cat "$unit.service" >/dev/null 2>&1; then
      state="$(systemctl is-active "$unit.service" 2>/dev/null || true)"
    else
      state="not-installed"
    fi
    printf '%-20s %s\n' "$unit" "$state"
  done
}

uninstall_app() {
  load_install_state
  validate_common
  if ((NON_INTERACTIVE == 0)); then
    echo "将停止服务并删除 $INSTALL_DIR 与 $CONFIG_DIR。"
    if ((PURGE == 0)); then
      echo "配置和 runtime 数据会先保存到 /var/backups/linux-autobook。"
    fi
    read -r -p "确认卸载？输入 YES: " answer
    [[ "$answer" == "YES" ]] || { echo "已取消"; exit 0; }
  fi

  for unit in autobook-admin.service autobook-gateway.service autobook-worker.service; do
    systemctl disable --now "$unit" 2>/dev/null || true
  done
  local backup=""
  if ((PURGE == 0)) && { [[ -d "$CONFIG_DIR" ]] || [[ -d "$INSTALL_DIR/runtime" ]]; }; then
    install -d -m 700 /var/backups/linux-autobook
    backup="/var/backups/linux-autobook/backup-$(date +%Y%m%d-%H%M%S).tar.gz"
    local items=()
    [[ -d "$CONFIG_DIR" ]] && items+=("${CONFIG_DIR#/}")
    [[ -d "$INSTALL_DIR/runtime" ]] && items+=("${INSTALL_DIR#/}/runtime")
    tar -C / -czf "$backup" "${items[@]}"
    chmod 600 "$backup"
  fi
  rm -f /etc/systemd/system/autobook-admin.service /etc/systemd/system/autobook-gateway.service /etc/systemd/system/autobook-worker.service
  rm -f /etc/letsencrypt/renewal-hooks/deploy/autobook-cert-deploy /usr/local/sbin/autobook-cert-deploy
  rm -rf -- "$INSTALL_DIR" "$CONFIG_DIR"
  systemctl daemon-reload
  systemctl reset-failed
  echo "linux-autobook 已卸载。"
  [[ -n "$backup" ]] && echo "配置/数据备份: $backup"
}

perform_update() {
  load_install_state
  [[ -z "$REPO_URL_OVERRIDE" ]] || REPO_URL="$REPO_URL_OVERRIDE"
  [[ -z "$REPO_BRANCH_OVERRIDE" ]] || REPO_BRANCH="$REPO_BRANCH_OVERRIDE"
  if [[ ! -r "$CONFIG_DIR/install.env" ]]; then
    echo "No existing installation found; use Install first." >&2
    exit 1
  fi
  local update_role="${INSTALL_ROLE:-all}"
  local update_domain="${TLS_DOMAIN:-}"
  local update_host="${PUBLIC_HOST:-}"
  local update_port="${ADMIN_PORT:-8766}"
  local tmp_dir
  tmp_dir="$(mktemp -d /tmp/linux-autobook-update.XXXXXX)"
  trap '[[ -n "${tmp_dir:-}" && "$tmp_dir" == /tmp/linux-autobook-update.* ]] && rm -rf -- "$tmp_dir"' EXIT
  git clone --depth 1 --branch "$REPO_BRANCH" "$REPO_URL" "$tmp_dir/source"
  bash "$tmp_dir/source/install.sh" --action install --role "$update_role" \
    --install-dir "$INSTALL_DIR" --admin-port "$update_port" \
    --public-host "$update_host" --domain "$update_domain" --non-interactive
  echo "Update completed from $REPO_URL ($REPO_BRANCH)."
}

if [[ -z "$ACTION" ]]; then
  if ((NON_INTERACTIVE == 0)) && [[ -t 0 ]]; then choose_action; else ACTION="install"; fi
fi
case "$ACTION" in
  status) show_status; exit 0 ;;
  uninstall) uninstall_app; exit 0 ;;
  update) perform_update; exit 0 ;;
  install) ;;
  *) echo "Invalid action: $ACTION" >&2; exit 2 ;;
esac

if [[ -z "$ROLE" ]]; then
  if ((NON_INTERACTIVE == 0)) && [[ -t 0 ]]; then choose_role; else ROLE="all"; fi
fi
if [[ "$ROLE" != "all" && "$ROLE" != "gateway" && "$ROLE" != "worker" ]]; then
  echo "Invalid role: $ROLE" >&2; exit 2
fi

if ((NON_INTERACTIVE == 0)) && [[ -t 0 ]]; then
  read -r -p "管理域名（已解析到本机则自动申请免费证书，留空使用自签名）: " input_domain
  DOMAIN="${input_domain:-$DOMAIN}"
  if [[ -n "$DOMAIN" ]]; then
    read -r -p "Let's Encrypt 通知邮箱（可留空）: " input_email
    ACME_EMAIL="${input_email:-$ACME_EMAIL}"
  else
    read -r -p "面板显示的公网 IP/主机名（留空自动检测）: " input_host
    PUBLIC_HOST="${input_host:-$PUBLIC_HOST}"
  fi
  read -r -p "管理面板端口 [$ADMIN_PORT]: " input_port
  ADMIN_PORT="${input_port:-$ADMIN_PORT}"
  if [[ "$ROLE" == "worker" ]]; then
    read -r -p "中心网关地址（例如 https://gateway.example.com:8765）: " input_gateway
    GATEWAY_URL="${input_gateway:-$GATEWAY_URL}"
    read -r -s -p "中心网关共享令牌（也可稍后在面板填写）: " input_token; echo
    GATEWAY_TOKEN="${input_token:-$GATEWAY_TOKEN}"
    read -r -p "自签名网关 CA 文件路径（公有证书留空）: " input_ca
    GATEWAY_CA_FILE="${input_ca:-$GATEWAY_CA_FILE}"
  fi
fi
validate_common

if [[ ! -f "$SOURCE_DIR/run_admin.py" || ! -d "$SOURCE_DIR/autobook_linux" ]]; then
  echo "install.sh must be run from a complete linux-autobook checkout." >&2
  exit 1
fi

if [[ -z "$PUBLIC_HOST" ]]; then
  if [[ -n "$DOMAIN" ]]; then
    PUBLIC_HOST="$DOMAIN"
  else
    PUBLIC_HOST="$(hostname -I 2>/dev/null | tr ' ' '\n' | grep -E '^[0-9]+(\.[0-9]+){3}$' | head -n1 || true)"
    [[ -n "$PUBLIC_HOST" ]] || PUBLIC_HOST="$(hostname -f 2>/dev/null || hostname)"
  fi
fi

WAS_GATEWAY_ACTIVE=0
WAS_WORKER_ACTIVE=0
systemctl is-active --quiet autobook-gateway.service 2>/dev/null && WAS_GATEWAY_ACTIVE=1 || true
systemctl is-active --quiet autobook-worker.service 2>/dev/null && WAS_WORKER_ACTIVE=1 || true

echo "[1/8] Installing system dependencies..."
export DEBIAN_FRONTEND=noninteractive
if command -v apt-get >/dev/null 2>&1; then
  apt-get update
  apt-get install -y git curl python3 python3-venv python3-pip p7zip-full aria2 openssl ca-certificates
  [[ -z "$DOMAIN" ]] || apt-get install -y certbot
else
  echo "This installer currently supports Debian/Ubuntu (apt-get)." >&2
  exit 1
fi

echo "[2/8] Installing application files..."
id autobook >/dev/null 2>&1 || useradd --system --home "$INSTALL_DIR" --shell /usr/sbin/nologin autobook
install -d -m 755 "$INSTALL_DIR"
if [[ "$(readlink -f "$SOURCE_DIR")" != "$(readlink -f "$INSTALL_DIR")" ]]; then
  tar -C "$SOURCE_DIR" --exclude=.git --exclude=.env --exclude=runtime --exclude=password.txt --exclude=.venv --exclude=__pycache__ -cf - . | tar -C "$INSTALL_DIR" -xf -
fi
install -d -m 750 -o autobook -g autobook "$INSTALL_DIR/runtime"
install -d -m 750 -o root -g autobook "$CONFIG_DIR"
if [[ ! -f "$INSTALL_DIR/password.txt" ]]; then
  install -m 600 -o autobook -g autobook "$INSTALL_DIR/password.example.txt" "$INSTALL_DIR/password.txt"
else
  chown autobook:autobook "$INSTALL_DIR/password.txt"
  chmod 600 "$INSTALL_DIR/password.txt"
fi

echo "[3/8] Creating Python environment..."
[[ -x "$INSTALL_DIR/.venv/bin/python" ]] || python3 -m venv "$INSTALL_DIR/.venv"
"$INSTALL_DIR/.venv/bin/python" -m pip install --upgrade pip
"$INSTALL_DIR/.venv/bin/pip" install -r "$INSTALL_DIR/requirements.txt"

set_env() {
  local file="$1" key="$2" value="$3" tmp
  [[ "$value" != *$'\n'* && "$value" != *$'\r'* ]] || { echo "Invalid newline in $key" >&2; exit 2; }
  tmp="${file}.tmp.$$"
  if [[ -f "$file" ]]; then
    awk -v key="$key" -v line="$key=$value" 'BEGIN{done=0} $0 ~ "^" key "=" {if(!done){print line; done=1}; next} {print} END{if(!done) print line}' "$file" > "$tmp"
  else
    printf '%s=%s\n' "$key" "$value" > "$tmp"
  fi
  install -m 600 -o root -g root "$tmp" "$file"
  rm -f "$tmp"
}

ensure_env() {
  local file="$1" key="$2" value="$3"
  grep -q "^${key}=" "$file" 2>/dev/null || set_env "$file" "$key" "$value"
}

read_env_value() {
  local file="$1" key="$2"
  sed -n "s/^${key}=//p" "$file" 2>/dev/null | tail -n1 | sed 's/^"//;s/"$//' || true
}

write_state() {
  local tls_mode="$1"
  {
    printf 'INSTALL_DIR=%q\n' "$INSTALL_DIR"
    printf 'CONFIG_DIR=%q\n' "$CONFIG_DIR"
    printf 'INSTALL_ROLE=%q\n' "$ROLE"
    printf 'PUBLIC_HOST=%q\n' "$PUBLIC_HOST"
    printf 'TLS_MODE=%q\n' "$tls_mode"
    printf 'TLS_DOMAIN=%q\n' "$DOMAIN"
    printf 'ADMIN_PORT=%q\n' "$ADMIN_PORT"
    printf 'REPO_URL=%q\n' "$REPO_URL"
    printf 'REPO_BRANCH=%q\n' "$REPO_BRANCH"
  } > "$CONFIG_DIR/install.env"
  chmod 600 "$CONFIG_DIR/install.env"
}

echo "[4/8] Creating role configuration..."
SHARED_TOKEN=""
[[ -f "$CONFIG_DIR/gateway.env" ]] && SHARED_TOKEN="$(read_env_value "$CONFIG_DIR/gateway.env" BAIDU_GATEWAY_TOKEN)"
[[ -n "$SHARED_TOKEN" || ! -f "$CONFIG_DIR/worker.env" ]] || SHARED_TOKEN="$(read_env_value "$CONFIG_DIR/worker.env" BAIDU_GATEWAY_TOKEN)"
[[ -z "$GATEWAY_TOKEN" ]] || SHARED_TOKEN="$GATEWAY_TOKEN"
if [[ -z "$SHARED_TOKEN" && "$ROLE" != "worker" ]]; then SHARED_TOKEN="$(openssl rand -hex 32)"; fi

if [[ "$ROLE" == "all" || "$ROLE" == "gateway" ]]; then
  [[ -f "$CONFIG_DIR/gateway.env" ]] || install -m 600 -o root -g root /dev/null "$CONFIG_DIR/gateway.env"
  ensure_env "$CONFIG_DIR/gateway.env" BAIDU_GATEWAY_TOKEN "$SHARED_TOKEN"
  ensure_env "$CONFIG_DIR/gateway.env" BAIDU_AUTH_FILE "$INSTALL_DIR/runtime/baidu_credentials.json"
  ensure_env "$CONFIG_DIR/gateway.env" BAIDU_GROUP_NAME "读秀12群"
  ensure_env "$CONFIG_DIR/gateway.env" BAIDU_GROUP_GID "498636198303058255"
  ensure_env "$CONFIG_DIR/gateway.env" BAIDU_SAVE_DIR "/autobook_inbox"
  ensure_env "$CONFIG_DIR/gateway.env" GATEWAY_BIND "0.0.0.0"
  ensure_env "$CONFIG_DIR/gateway.env" GATEWAY_PORT "8765"
  set_env "$CONFIG_DIR/gateway.env" GATEWAY_TLS_CERT "$INSTALL_DIR/runtime/gateway.crt"
  set_env "$CONFIG_DIR/gateway.env" GATEWAY_TLS_KEY "$INSTALL_DIR/runtime/gateway.key"
  ensure_env "$CONFIG_DIR/gateway.env" GATEWAY_CONCURRENCY "3"
  ensure_env "$CONFIG_DIR/gateway.env" GATEWAY_CACHE_TTL_SECONDS "3600"
  ensure_env "$CONFIG_DIR/gateway.env" GATEWAY_JOB_ROOT "$INSTALL_DIR/runtime/gateway/jobs"
fi

if [[ "$ROLE" == "all" || "$ROLE" == "worker" ]]; then
  [[ -f "$CONFIG_DIR/worker.env" ]] || install -m 600 -o root -g root /dev/null "$CONFIG_DIR/worker.env"
  ensure_env "$CONFIG_DIR/worker.env" SITE_BASE_URL "https://544544.xyz"
  ensure_env "$CONFIG_DIR/worker.env" WORKER_TOKEN ""
  ensure_env "$CONFIG_DIR/worker.env" WORKER_ID "$(hostname -s)-worker"
  ensure_env "$CONFIG_DIR/worker.env" WORKER_QUEUE "pdf"
  ensure_env "$CONFIG_DIR/worker.env" POLL_SECONDS "15"
  ensure_env "$CONFIG_DIR/worker.env" CONCURRENCY "3"
  ensure_env "$CONFIG_DIR/worker.env" LEASE_HEARTBEAT_SECONDS "60"
  if [[ "$ROLE" == "all" ]]; then
    if [[ -n "$DOMAIN" ]]; then
      DEFAULT_GATEWAY_URL="https://${DOMAIN}:8765"
      DEFAULT_GATEWAY_CA=""
    else
      DEFAULT_GATEWAY_URL="https://127.0.0.1:8765"
      DEFAULT_GATEWAY_CA="$INSTALL_DIR/runtime/gateway.crt"
    fi
  else
    DEFAULT_GATEWAY_URL="$GATEWAY_URL"
    DEFAULT_GATEWAY_CA="$GATEWAY_CA_FILE"
  fi
  ensure_env "$CONFIG_DIR/worker.env" BAIDU_GATEWAY_URL "$DEFAULT_GATEWAY_URL"
  ensure_env "$CONFIG_DIR/worker.env" BAIDU_GATEWAY_TOKEN "$SHARED_TOKEN"
  ensure_env "$CONFIG_DIR/worker.env" BAIDU_GATEWAY_CA_FILE "$DEFAULT_GATEWAY_CA"
  ensure_env "$CONFIG_DIR/worker.env" BAIDU_GATEWAY_TIMEOUT_SECONDS "7200"
  ensure_env "$CONFIG_DIR/worker.env" BAIDU_GATEWAY_POLL_SECONDS "3"
  ensure_env "$CONFIG_DIR/worker.env" WORK_ROOT "$INSTALL_DIR/runtime/work"
  ensure_env "$CONFIG_DIR/worker.env" DOWNLOAD_ROOT "$INSTALL_DIR/runtime/downloads"
  ensure_env "$CONFIG_DIR/worker.env" INDEX_DB "$INSTALL_DIR/runtime/library_index.sqlite3"
  ensure_env "$CONFIG_DIR/worker.env" PASSWORD_DICT "$INSTALL_DIR/password.txt"
  ensure_env "$CONFIG_DIR/worker.env" SEVEN_ZIP_BIN "7z"
  ensure_env "$CONFIG_DIR/worker.env" ARIA2C_BIN "aria2c"
  ensure_env "$CONFIG_DIR/worker.env" PDG_DPI "200"
  ensure_env "$CONFIG_DIR/worker.env" DRIVE_EMAIL ""
  ensure_env "$CONFIG_DIR/worker.env" DRIVE_PASSWORD ""
  ensure_env "$CONFIG_DIR/worker.env" DRIVE_BASE_URL "https://drive.netupdown.com"
  ensure_env "$CONFIG_DIR/worker.env" DRIVE_TARGET_DIR "transfer"
  ensure_env "$CONFIG_DIR/worker.env" DRIVE_EXPIRE_DAYS "7"
fi
chmod 600 "$CONFIG_DIR"/*.env

cat > "$CONFIG_DIR/admin.env" <<EOF
ADMIN_BIND=$ADMIN_BIND
ADMIN_PORT=$ADMIN_PORT
ADMIN_TLS_CERT=$CONFIG_DIR/admin.crt
ADMIN_TLS_KEY=$CONFIG_DIR/admin.key
ADMIN_STATE_FILE=$CONFIG_DIR/admin-state.json
ADMIN_GATEWAY_ENV=$CONFIG_DIR/gateway.env
ADMIN_WORKER_ENV=$CONFIG_DIR/worker.env
ADMIN_SESSION_SECONDS=28800
ADMIN_PUBLIC_HOST=$PUBLIC_HOST
ADMIN_ROLE=$ROLE
EOF
chmod 600 "$CONFIG_DIR/admin.env"
write_state "self-signed"

echo "[5/8] Creating HTTPS certificates..."
if [[ "$PUBLIC_HOST" =~ ^[0-9]+(\.[0-9]+){3}$ || "$PUBLIC_HOST" == *:* ]]; then PUBLIC_SAN="IP:${PUBLIC_HOST}"; else PUBLIC_SAN="DNS:${PUBLIC_HOST}"; fi
generate_self_signed() {
  local cert="$1" key="$2" owner="$3" group="$4"
  local valid=0
  if [[ -s "$cert" && -s "$key" ]]; then
    if [[ "$PUBLIC_HOST" =~ ^[0-9]+(\.[0-9]+){3}$ ]]; then openssl x509 -in "$cert" -noout -checkip "$PUBLIC_HOST" >/dev/null 2>&1 && valid=1 || true
    else openssl x509 -in "$cert" -noout -checkhost "$PUBLIC_HOST" >/dev/null 2>&1 && valid=1 || true
    fi
  fi
  if ((valid == 0)); then
    rm -f "$cert" "$key"
    openssl req -x509 -newkey rsa:3072 -sha256 -nodes -days 825 -keyout "$key" -out "$cert" \
      -subj "/CN=${PUBLIC_HOST}" -addext "subjectAltName=${PUBLIC_SAN},DNS:localhost,IP:127.0.0.1" >/dev/null 2>&1
  fi
  chown "$owner:$group" "$cert" "$key"; chmod 644 "$cert"; chmod 640 "$key"
}
generate_self_signed "$CONFIG_DIR/admin.crt" "$CONFIG_DIR/admin.key" root root
if [[ "$ROLE" == "all" || "$ROLE" == "gateway" ]]; then
  generate_self_signed "$INSTALL_DIR/runtime/gateway.crt" "$INSTALL_DIR/runtime/gateway.key" autobook autobook
fi

install -m 755 -o root -g root "$INSTALL_DIR/deploy/autobook-cert-deploy.sh" /usr/local/sbin/autobook-cert-deploy
if [[ -n "$DOMAIN" ]]; then
  if command -v ufw >/dev/null 2>&1 && ufw status | grep -q '^Status: active'; then ufw allow 80/tcp comment 'ACME HTTP-01' >/dev/null; fi
  install -d -m 755 /etc/letsencrypt/renewal-hooks/deploy
  ln -sfn /usr/local/sbin/autobook-cert-deploy /etc/letsencrypt/renewal-hooks/deploy/autobook-cert-deploy
  cert_ok=0
  if [[ -s "/etc/letsencrypt/live/$DOMAIN/fullchain.pem" ]]; then cert_ok=1; else
    cert_args=(certonly --standalone --non-interactive --agree-tos --preferred-challenges http -d "$DOMAIN")
    if [[ -n "$ACME_EMAIL" ]]; then cert_args+=(--email "$ACME_EMAIL"); else cert_args+=(--register-unsafely-without-email); fi
    certbot "${cert_args[@]}" && cert_ok=1 || true
  fi
  if ((cert_ok == 1)); then
    write_state "letsencrypt"
    /usr/local/sbin/autobook-cert-deploy
    if [[ "$ROLE" == "all" ]]; then
      set_env "$CONFIG_DIR/worker.env" BAIDU_GATEWAY_URL "https://${DOMAIN}:8765"
      set_env "$CONFIG_DIR/worker.env" BAIDU_GATEWAY_CA_FILE ""
    fi
  else
    echo "WARNING: Let's Encrypt issuance failed. Keeping a self-signed certificate." >&2
    echo "Check that $DOMAIN resolves here and inbound port 80 is open, then rerun the installer." >&2
    if [[ "$ROLE" == "all" ]]; then
      set_env "$CONFIG_DIR/worker.env" BAIDU_GATEWAY_URL "https://127.0.0.1:8765"
      set_env "$CONFIG_DIR/worker.env" BAIDU_GATEWAY_CA_FILE "$INSTALL_DIR/runtime/gateway.crt"
    fi
  fi
fi

echo "[6/8] Installing systemd services..."
install_unit() { sed "s|/opt/autobook-linux|$INSTALL_DIR|g" "$1" > "$2"; chmod 644 "$2"; }
install_unit "$INSTALL_DIR/deploy/autobook-admin.service" /etc/systemd/system/autobook-admin.service
if [[ "$ROLE" == "all" || "$ROLE" == "gateway" ]]; then
  install_unit "$INSTALL_DIR/deploy/autobook-gateway.service" /etc/systemd/system/autobook-gateway.service
else
  systemctl disable --now autobook-gateway.service 2>/dev/null || true
  rm -f /etc/systemd/system/autobook-gateway.service
fi
if [[ "$ROLE" == "all" || "$ROLE" == "worker" ]]; then
  install_unit "$INSTALL_DIR/deploy/autobook-worker.service" /etc/systemd/system/autobook-worker.service
else
  systemctl disable --now autobook-worker.service 2>/dev/null || true
  rm -f /etc/systemd/system/autobook-worker.service
fi
systemctl daemon-reload
if [[ "$ROLE" == "all" || "$ROLE" == "gateway" ]]; then systemctl enable autobook-gateway.service >/dev/null; fi
if [[ "$ROLE" == "all" || "$ROLE" == "worker" ]]; then systemctl enable autobook-worker.service >/dev/null; fi
systemctl enable autobook-admin.service >/dev/null
systemctl restart autobook-admin.service
if [[ "$ROLE" == "all" || "$ROLE" == "gateway" ]] && ((WAS_GATEWAY_ACTIVE == 1)); then
  systemctl restart autobook-gateway.service
fi
if [[ "$ROLE" == "all" || "$ROLE" == "worker" ]] && ((WAS_WORKER_ACTIVE == 1)); then
  systemctl restart autobook-worker.service
fi

echo "[7/8] Running tests and service checks..."
cd "$INSTALL_DIR"
"$INSTALL_DIR/.venv/bin/python" -m unittest discover -s tests -q
panel_ready=0
for _ in {1..15}; do
  if curl -kfsS "https://127.0.0.1:${ADMIN_PORT}/health" >/dev/null 2>&1; then panel_ready=1; break; fi
  sleep 1
done
((panel_ready == 1)) || { journalctl -u autobook-admin -n 30 --no-pager; echo "Admin panel failed to become ready" >&2; exit 1; }

echo "[8/8] Updating firewall rules when UFW is active..."
if command -v ufw >/dev/null 2>&1 && ufw status | grep -q '^Status: active'; then
  ufw allow "${ADMIN_PORT}/tcp" comment 'linux-autobook admin' >/dev/null
  if [[ "$ROLE" == "all" || "$ROLE" == "gateway" ]]; then ufw allow 8765/tcp comment 'linux-autobook gateway' >/dev/null; fi
fi

if [[ "$PUBLIC_HOST" == *:* ]]; then PANEL_URL="https://[${PUBLIC_HOST}]:${ADMIN_PORT}/"; else PANEL_URL="https://${PUBLIC_HOST}:${ADMIN_PORT}/"; fi
TLS_MODE="$(sed -n 's/^TLS_MODE=//p' "$CONFIG_DIR/install.env" | tr -d "'")"
echo
echo "============================================================"
echo " linux-autobook installation completed"
echo " Role: $ROLE"
echo " TLS:  $TLS_MODE"
echo " Admin panel: $PANEL_URL"
echo " Default username: admin"
echo " Default password: admin"
echo " Open Quick Setup in the panel; incomplete roles stay stopped."
echo " Run this script again without arguments for update/status/uninstall menus."
echo "============================================================"
