#!/usr/bin/env bash
set -Eeuo pipefail

STATE_FILE="/etc/linux-autobook/install.env"
if [[ ! -r "$STATE_FILE" ]]; then
  echo "linux-autobook install state not found: $STATE_FILE" >&2
  exit 1
fi

# This file is generated by install.sh, owned by root and never user-editable
# through the web panel.
# shellcheck disable=SC1090
source "$STATE_FILE"

: "${INSTALL_DIR:=/opt/autobook-linux}"
: "${CONFIG_DIR:=/etc/linux-autobook}"
: "${INSTALL_ROLE:=all}"
: "${TLS_DOMAIN:?TLS_DOMAIN is required}"

LIVE_DIR="/etc/letsencrypt/live/${TLS_DOMAIN}"
if [[ ! -s "$LIVE_DIR/fullchain.pem" || ! -s "$LIVE_DIR/privkey.pem" ]]; then
  echo "Let's Encrypt certificate is incomplete for $TLS_DOMAIN" >&2
  exit 1
fi

install -m 644 -o root -g root "$LIVE_DIR/fullchain.pem" "$CONFIG_DIR/admin.crt"
install -m 640 -o root -g root "$LIVE_DIR/privkey.pem" "$CONFIG_DIR/admin.key"

if [[ "$INSTALL_ROLE" == "all" || "$INSTALL_ROLE" == "gateway" ]]; then
  install -d -m 750 -o autobook -g autobook "$INSTALL_DIR/runtime"
  install -m 644 -o autobook -g autobook "$LIVE_DIR/fullchain.pem" "$INSTALL_DIR/runtime/gateway.crt"
  install -m 640 -o autobook -g autobook "$LIVE_DIR/privkey.pem" "$INSTALL_DIR/runtime/gateway.key"
fi

systemctl try-restart autobook-admin.service 2>/dev/null || true
if [[ "$INSTALL_ROLE" == "all" || "$INSTALL_ROLE" == "gateway" ]]; then
  systemctl try-restart autobook-gateway.service 2>/dev/null || true
fi

echo "linux-autobook certificates deployed for $TLS_DOMAIN"
